# Generated by Django 4.2.4 on 2023-09-03 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailingmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='clients',
            field=models.ManyToManyField(to='main.client', verbose_name='Клиенты'),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='logs',
            field=models.ManyToManyField(to='main.logservers', verbose_name='Logs'),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='mailing_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailingsettings', verbose_name='Настройка'),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailingmessage', verbose_name='Письмо'),
        ),
        migrations.AddField(
            model_name='mailingattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logservers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
